### ISSUE TITLE
Add a test case to move a slider and create a special slider method 

### ISSUE THREAD

**Issue by jseng92** [Xceptance/neodymium-showcase#14]
add a showcase how a slider on a webpage can be drag and dropped 

add an example how the user can create a special method based on the generell slider function 

generell one: 

public static void dragAndDropUntilCondition(SelenideElement elementToMove, SelenideElement elementToCheck, int horizontalMovement, int verticalMovement,
                                                 int pauseBetweenMovements, int retryMovements, Condition condition)
    {
        Actions moveSlider = new Actions(Neodymium.getDriver());

        int counter = 0;
        while (!elementToCheck.has(condition))
        {
            if (counter > retryMovements)
            {
                SelenideAddons.wrapAssertionError(() -> {
                    Assert.assertTrue("CircutBreaker: Was not able to move the element and to reach the condition. Tried: " + retryMovements
                                      + " times to move the element.", false);
                });
            }
            Action action = moveSlider.dragAndDropBy(elementToMove.getWrappedElement(), horizontalMovement, verticalMovement).build();
            action.perform();
            Selenide.sleep(pauseBetweenMovements);
            counter++;
        }
    }

a special one: 

private void leftHorizontalDragAndDropUntilText(SelenideElement elementToMove, SelenideElement elementToCheck, int horizontalMovement,
                                                    String sliderValueAttributeName, String moveUntil)
    {
        SelenideAddons.dragAndDropUntilCondition(elementToMove, elementToCheck, horizontalMovement, 0, 3000, 10,
                                                 Condition.attribute(sliderValueAttributeName, moveUntil));
    }

more Informations are given inside the doc and in the code

**Comment by jseng92** [comment]
`public static void dragAndDropUntilCondition(SelenideElement elementToMove, SelenideElement elementToCheck, int horizontalMovement, int verticalMovement,
int pauseBetweenMovements, int retryMovements, Condition condition)
{
Actions moveSlider = new Actions(Neodymium.getDriver());

    int counter = 0;
    while (!elementToCheck.has(condition))
    {
        if (counter > retryMovements)
        {
            SelenideAddons.wrapAssertionError(() -> {
                Assert.assertTrue("CircutBreaker: Was not able to move the element and to reach the condition. Tried: " + retryMovements
                                  + " times to move the element.", false);
            });
        }
        Action action = moveSlider.dragAndDropBy(elementToMove.getWrappedElement(), horizontalMovement, verticalMovement).build();
        action.perform();
        Selenide.sleep(pauseBetweenMovements);
        counter++;
    }
}`

**Comment by jseng92** [comment]
add a first test for a horizontal movement

**Comment by occupant23** [comment]
done
