### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#22]
We need to make sure that users of the showcase project understands what parts in the test code (test classes) are only for demo purposes and would be transferred to the configuration files.

Tasks:
- [ ] add comments that tell the user when configurations are only added for demo reasons
- [ ] add commented parts in the configuration for every test case that can be copied (add the name of the test case to every block in order that it can be linked)
- [ ] add an information block to the README to emphasize that this is a collection of single tests and code snippets to provide an easy hands on experience and that running it all together can lead to errors due to the demo character and the different configurations needed for different systems under test

**Comment by occupant23** [comment]
@jseng92 Please open a feature branch for this and start with one test case. Doing so we can discuss if this matches our intentions.

**Comment by jseng92** [comment]
made some updates in BasicAuthenticationTest.java and README.md

**Comment by jseng92** [comment]
update docu for CheckboxTest & TextTest

**Comment by jseng92** [comment]
added some words to the slider test case

**Comment by jseng92** [comment]
added requested changes
