### ISSUE TITLE
Fix the checkbox test

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#23]
I get the following issue:

>  CheckboxTest.testSimpleShadowDOM:100 Invalid element state: element click intercepted: Element <mwc-checkbox></mwc-checkbox> is not clickable at point (222, 20). Other element would receive the click: <span>...</span>

**Comment by jseng92** [comment]
works now without any code changes 
maybe the site was updated 

this issue can be closed for now
