### ISSUE TITLE
Showcase Neodymium.getRandom()

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#25]
Please add a show case and demonstrate the usage of Neodymium.getRandom().

Add a second show case to demonstrate the usage of the Fixed Random support (Configuring the initial seed for the Random object). 

The test case could be clicking a random element on a list page and validation the choice on the resulting detail page.
(e.g. job offers at Xceptance)

**Comment by occupant23** [comment]
done with https://github.com/Xceptance/neodymium-showcase/pull/26
Needs to be merged into master.

**Comment by occupant23** [comment]
@georgkunze Please recheck if this is easy to understand and works as a show case.

**Comment by georgkunze** [comment]
@occupant23 Rechecked! Is understandable. I would maybe add more examples, to show the usage.

**Comment by occupant23** [comment]
@georgkunze will inform you, when the extension is ready

**Comment by occupant23** [comment]
@georgkunze Please review this again
