### ISSUE TITLE
Showcase how to validate and perform actions within an iFrame

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#28]
- [x] Feature branch
- [x] Create a package with at least one test class for this
- [x] Look at the other packages and try to implement the same style
- [x] Create a PR when done

https://github.com/Xceptance/neodymium-library/wiki/IFrame-handling

**Comment by AJakobi** [comment]
Branchname: #28-Validate-and-perform-actions-in-iFrame
Package: showcase.neodymium.tests.iframe
Class: SwitchToFrame

just added the first methods I want to use

**Comment by occupant23** [comment]
@ufjena Please perform the requested changes from the PR. Thanks
