### ISSUE TITLE
Showcase how to work with log4j

### ISSUE THREAD

**Issue by ufjena** [Xceptance/neodymium-showcase#29]

**Comment by occupant23** [comment]
Done with https://github.com/Xceptance/neodymium-showcase/pull/26
Needs to be merged into master.

**Comment by occupant23** [comment]
@georgkunze Please recheck if this is easy to understand and works as a show case.

**Comment by georgkunze** [comment]
@occupant23 Rechecked!

**Comment by ufjena** [comment]
done
