### ISSUE TITLE
Showcase DataUtils

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#30]
- [ ] Feature branch
- [ ] Create a package with test classes for separate aspects of DataUtils
  - Retrieve data via direct access e.g. asString, asDouble
  - Retrieve data via JSONPath 
  - Retrieve a POJO
- [ ] Look at the other packages and try to implement the same style
- [ ] Create a PR when done

Documentation:
https://github.com/Xceptance/neodymium-library/wiki/Test-data-provider
https://github.com/Xceptance/neodymium-library/wiki/Utility-classes#datautils

**Comment by rkl-xc** [comment]
Add a pull request and another optional one.

**Comment by occupant23** [comment]
done thx

**Comment by occupant23** [comment]
@georgkunze Please recheck if this is easy to understand and works as a show case.

**Comment by georgkunze** [comment]
@occupant23 Recheck done. Showcases are good.

**Comment by ufjena** [comment]
done
