### ISSUE TITLE
Deactivate highlight mode

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#4]
Our highlighting solution seems not to be able to perform within a shadow dom. Please deactivate it for the project.
Add a note within the neodymium library wiki that states, that highlighting of shadow dom elements is not supported at the moment and it should be deactivated if you are testing them.

**Comment by georgkunze** [comment]
I checked in the changes to the wiki in the neodymium-library.wiki-project(in development branch)

**Comment by occupant23** [comment]
rechecked and merged into development
